const SYMBOLS=[{key:'W',letter:'W',cls:'word',value:10,weight:14},{key:'O',letter:'O',cls:'word',value:10,weight:14},{key:'R',letter:'R',cls:'word',value:10,weight:14},{key:'D',letter:'D',cls:'word',value:12,weight:12},{key:'P',letter:'P',cls:'word',value:12,weight:10},{key:'L',letter:'L',cls:'word',value:14,weight:10},{key:'A',letter:'A',cls:'word',value:12,weight:10},{key:'Y',letter:'Y',cls:'word',value:18,weight:8},{key:'HEADPHONES',emoji:'🎧',cls:'music',value:22,weight:6},{key:'CASSETTE',emoji:'📼',cls:'music',value:24,weight:5},{key:'VINYL',emoji:'💿',cls:'music',value:26,weight:5},{key:'BONUS',emoji:'📺',cls:'bonus',value:35,weight:3},{key:'FREE',emoji:'🌆',cls:'free',value:0,weight:3},{key:'WILD',emoji:'🐻',cls:'wild',value:70,weight:2},{key:'JACKPOT',emoji:'⚡',cls:'jackpot',value:100,weight:1}];
const weighted=SYMBOLS.flatMap(s=>Array(s.weight).fill(s));
const $=id=>document.getElementById(id);
const reelsEl=$('reels'),creditsEl=$('credits'),betDisplay=$('betDisplay'),lastWin=$('lastWin'),freeSpinsEl=$('freeSpins'),statusText=$('statusText'),logEl=$('log');
const miniPot=$('miniPot'),majorPot=$('majorPot'),neonPot=$('neonPot');
let credits=Number(localStorage.getItem('wordplayCredits')||2500),bet=25,freeSpins=0,autoSpin=false,autoTimer=null,spinning=false,totalSpins=Number(localStorage.getItem('wordplaySpins')||0),biggestWin=Number(localStorage.getItem('wordplayBiggest')||0);let pots={mini:125,major:750,neon:2500};
function rand(){return weighted[Math.floor(Math.random()*weighted.length)]}
function symbolHTML(sym){if(sym.letter)return `<span class="tile">${sym.letter}</span>`;return `<span class="emoji">${sym.emoji}</span><small>${sym.key}</small>`}
function render(board=[]){reelsEl.innerHTML='';for(let c=0;c<5;c++){const reel=document.createElement('div');reel.className='reel';for(let r=0;r<3;r++){const sym=board[c]?.[r]||rand();const div=document.createElement('div');div.className=`symbol ${sym.cls}`;div.dataset.key=sym.key;div.innerHTML=symbolHTML(sym);reel.appendChild(div)}reelsEl.appendChild(reel)}}
function save(){localStorage.setItem('wordplayCredits',credits);localStorage.setItem('wordplaySpins',totalSpins);localStorage.setItem('wordplayBiggest',biggestWin)}
function update(){creditsEl.textContent=credits;betDisplay.textContent=bet;freeSpinsEl.textContent=freeSpins;miniPot.textContent=pots.mini;majorPot.textContent=pots.major;neonPot.textContent=pots.neon;save()}
function log(t){const d=document.createElement('div');d.textContent=t;logEl.prepend(d);while(logEl.children.length>12)logEl.lastChild.remove()}
function lines(b){return[[b[0][0],b[1][0],b[2][0],b[3][0],b[4][0]],[b[0][1],b[1][1],b[2][1],b[3][1],b[4][1]],[b[0][2],b[1][2],b[2][2],b[3][2],b[4][2]],[b[0][0],b[1][1],b[2][2],b[3][1],b[4][0]],[b[0][2],b[1][1],b[2][0],b[3][1],b[4][2]]]}
function match(line){const base=line.find(s=>s.key!=='WILD');if(!base)return true;return line.every(s=>s.key===base.key||s.key==='WILD')}
function evaluate(board){let win=0,free=0;lines(board).forEach(line=>{if(match(line))win+=Math.floor(line.reduce((a,b)=>a+b.value,0)*bet/4)});board.flat().forEach(s=>{if(s.key==='BONUS')win+=bet*2;if(s.key==='FREE')free+=3;if(s.key==='JACKPOT')win+=bet*25});return{win,free}}
function flashWin(){document.body.classList.add('winflash');setTimeout(()=>document.body.classList.remove('winflash'),700)}
async function spin(){if(spinning)return;if(credits<bet&&freeSpins<=0){statusText.textContent='Out of fake credits. Hit reset, fake capitalism forgives.';stopAuto();return}spinning=true;$('spinBtn').disabled=true;if(freeSpins>0)freeSpins--;else credits-=bet;totalSpins++;update();document.querySelectorAll('.symbol').forEach(s=>s.classList.add('spin'));statusText.textContent='SPINNING...';await new Promise(r=>setTimeout(r,950));const board=[];for(let c=0;c<5;c++){board[c]=[];for(let r=0;r<3;r++)board[c][r]=rand()}render(board);const result=evaluate(board);credits+=result.win;freeSpins+=result.free;lastWin.textContent=result.win;if(result.win>biggestWin)biggestWin=result.win;if(result.win>0){pots.mini+=5;pots.major+=10;pots.neon+=15;statusText.textContent=`BIG WORD ENERGY • WON ${result.win}`;document.querySelectorAll('.symbol').forEach(s=>s.classList.add('win'));setTimeout(()=>document.querySelectorAll('.symbol').forEach(s=>s.classList.remove('win')),850);flashWin();log(`Won ${result.win} credits.`)}else{lastWin.textContent='0';statusText.textContent='No hit. The skyline remains unimpressed.';log('Spin missed.')}if(result.free>0){statusText.textContent+=` • ${result.free} FREE SPINS`;log(`Awarded ${result.free} free spins.`)}update();spinning=false;$('spinBtn').disabled=false}
$('spinBtn').addEventListener('click',spin);$('betUp').addEventListener('click',()=>{bet=Math.min(500,bet+25);update()});$('betDown').addEventListener('click',()=>{bet=Math.max(25,bet-25);update()});$('resetBtn').addEventListener('click',()=>{credits=2500;bet=25;freeSpins=0;lastWin.textContent='0';statusText.textContent='Fresh fake credits injected.';stopAuto();render();update();log('Machine reset.')});
function stopAuto(){autoSpin=false;clearTimeout(autoTimer);$('autoSpinBtn').textContent='AUTO: OFF'}
function autoLoop(){if(!autoSpin)return;spin();autoTimer=setTimeout(autoLoop,1750)}
$('autoSpinBtn').addEventListener('click',()=>{autoSpin=!autoSpin;if(autoSpin){$('autoSpinBtn').textContent='AUTO: ON';autoLoop()}else stopAuto()});
render();update();log(`WORDPLAY live. Spins: ${totalSpins}. Biggest win: ${biggestWin}.`);